# Generated by Django 4.0.5 on 2022-07-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tier', to='users.tier'),
        ),
    ]
