# Generated by Django 4.0.5 on 2022-07-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='sizes',
            field=models.CharField(choices=[('small', 200), ('medium', 400)], default=200, max_length=50),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(choices=[(1, 'BASIC'), (2, 'PREMIUM'), (3, 'ENTERPRISE')], default='BASIC', max_length=50, unique=True, verbose_name='tier'),
        ),
    ]
