# Generated by Django 4.0.5 on 2022-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tier_sizes_alter_tier_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('PREMIUM', 'PREMIUM'), ('ENTERPRISE', 'ENTERPRISE')], default='BASIC', max_length=50, unique=True, verbose_name='tier'),
        ),
    ]
