# Generated by Django 4.0.5 on 2022-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_tier_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(choices=[('basic', 'BASIC'), ('premium', 'PREMIUM'), ('enterprise', 'ENTERPRISE')], default='BASIC', max_length=50, unique=True, verbose_name='tier'),
        ),
    ]
