# Generated by Django 4.0.5 on 2022-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0002_imagemodel_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='thumbnail',
            new_name='thumbnail_200px',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail_400px',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
