# Generated by Django 4.0.5 on 2022-07-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0003_remove_userimage_user_userimage_custom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='thumbnail_200px',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='thumbnail_400px',
        ),
        migrations.AddField(
            model_name='userimage',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='images_app.thumbnail'),
        ),
    ]
