# Generated by Django 4.0.5 on 2022-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0004_client_imagemodel_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
