# Generated by Django 4.0.5 on 2022-07-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0005_remove_thumbnail_thumbnail_thumbnail_thumbnail_200px_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='thumbnail_200px',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='thumbnail_400px',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='images_app.userimage'),
        ),
    ]
