# Generated by Django 4.0.5 on 2022-07-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0007_remove_userimage_image_userimage_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='images_app.thumbnail'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
