# Generated by Django 4.0.5 on 2022-07-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0008_userimage_thumbnail_alter_thumbnail_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='images_app.userimage'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
