# Generated by Django 4.0.5 on 2022-07-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0010_remove_userimage_thumbnail_thumbnail_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='chose_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chose_image', to='images_app.userimage'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
