# Generated by Django 4.0.5 on 2022-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0011_thumbnail_chose_image_alter_thumbnail_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
