# Generated by Django 4.0.5 on 2022-07-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0012_thumbnail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='chose_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_thumbnail', to='images_app.userimage'),
        ),
    ]
