# Generated by Django 4.0.5 on 2022-07-08 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images_app', '0014_thumbnail_custom_user_alter_thumbnail_chose_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='custom_user',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='custom_user',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_thumbnail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
