# Generated by Django 4.0.5 on 2022-07-09 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images_app', '0016_remove_thumbnail_chose_image_thumbnail_choose_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='choose_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='images_app.userimage'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to=settings.AUTH_USER_MODEL),
        ),
    ]
